controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    human_effort_controller:
      type: effort_controllers/JointGroupEffortController
    
    yr_effort_controller:
      type: effort_controllers/JointGroupEffortController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

human_effort_controller:
  ros__parameters:
    joints:
      - human_l_thigh_abduction_joint
      - human_l_thigh_flexion_joint
      - human_l_thigh_rotation_joint
      - human_l_kne_joint
      - human_l_ank_joint
      - human_r_thigh_abduction_joint
      - human_r_thigh_flexion_joint
      - human_r_thigh_rotation_joint
      - human_r_kne_joint
      - human_r_ank_joint

yr_effort_controller:
  ros__parameters:
    joints:
      - yr_l_pel_joint
      - yr_l_hip_joint
      - yr_l_kne_joint
      - yr_l_ank_joint
      - yr_r_pel_joint
      - yr_r_hip_joint
      - yr_r_kne_joint
      - yr_r_ank_joint