<?xml version="1.0"?>
<robot name="lower_limb_exoskeleton" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="properties.xacro" />
    <xacro:include filename="macros.xacro" />

    <!-- ======================================================= -->
    <!-- LINKS                                                   -->
    <!-- ======================================================= -->
    <!-- <xacro:create_link name="waist_link" m="${waist_m}" l="${waist_l}"
        w="${waist_w}" h="${waist_h}" mat="${waist_mat}" /> -->
    <xacro:create_link2 name="waist_link" m="${waist_m}" l="${waist_l}" w="${waist_w}"
        h="${waist_h}" o_x="0" o_y="${waist_mesh_w/2}" o_z="${-waist_h_offset}" o_r="0" o_p="${-PI}"
        o_yaw="${-PI}"
        mat="${waist_mat}"
        mesh_filename="${waist_mesh}" mirror="1" />

    <!-- <xacro:create_link2 name="l_pel_link" m="${pel_m}" l="${pel_l}"
    w="${pel_w}"
        h="${pel_h}" o_x="0" o_y="${waist_w/2}" o_z="0" o_r="0" o_p="0"
        o_yaw="${PI/2}" mat="${pel_mat}" mesh_filename="${pel_mesh}" mirror="1" /> -->
    <xacro:create_link2 name="l_pel_link" m="${pel_m}" l="${pel_l}" w="${pel_w}"
        h="${pel_h}" o_x="${pel_x_offset}" o_y="${pel_y_offset}"
        o_z="${-pel_h_offset}" o_r="0.0" o_p="0"
        o_yaw="0" mat="${pel_mat}" mesh_filename="${pel_mesh}" mirror="1" />
    <xacro:create_link2 name="l_thigh_link" m="${thigh_m}" l="${thigh_l}" w="${thigh_w}"
        h="${thigh_h}" o_x="${thigh_w}" o_y="${thigh_w/2}" o_z="${-thigh_l}" o_r="0" o_p="0"
        o_yaw="${PI}" mat="${thigh_mat}" mesh_filename="${thigh_mesh}" mirror="1" />
    <xacro:create_link2 name="l_shank_link" m="${shank_m}" l="${shank_l}" w="${shank_w}"
        h="${shank_h}" o_x="${shank_w}" o_y="${shank_w/2}" o_z="${-shank_l}" o_r="0" o_p="0"
        o_yaw="${PI}"
        mat="${shank_mat}" mesh_filename="${shank_mesh}" mirror="1" />
    <xacro:create_link2 name="l_foot_link" m="${foot_m}" l="${foot_l}" w="${foot_w}"
        h="${foot_h}" o_x="${-foot_h}" o_y="${foot_w}" o_z="${-foot_l}" o_r="0" o_p="0" o_yaw="0"
        mat="${foot_mat}"
        mesh_filename="${foot_mesh}" mirror="-1" />

    <xacro:create_link2 name="r_pel_link" m="${pel_m}" l="${pel_l}" w="${pel_w}"
        h="${pel_h}" o_x="${pel_x_offset}" o_y="${pel_y_offset}"
        o_z="${-pel_h_offset}" o_r="0" o_p="0"
        o_yaw="0" mat="${pel_mat}" mesh_filename="${pel_mesh}" mirror="1" />
    <xacro:create_link2 name="r_thigh_link" m="${thigh_m}" l="${thigh_l}" w="${thigh_w}"
        h="${thigh_h}" o_x="${-thigh_w}" o_y="${-thigh_w/2}" o_z="${-thigh_l}" o_r="0" o_p="0"
        o_yaw="0" mat="${thigh_mat}" mesh_filename="${thigh_mesh}" mirror="1" />
    <xacro:create_link2 name="r_shank_link" m="${shank_m}" l="${shank_l}" w="${shank_w}"
        h="${shank_h}" o_x="${-shank_w}" o_y="${-shank_w/2}" o_z="${-shank_l}" o_r="0" o_p="0" o_yaw="0"
        mat="${shank_mat}" mesh_filename="${shank_mesh}" mirror="1" />
    <xacro:create_link2 name="r_foot_link" m="${foot_m}" l="${foot_l}" w="${foot_w}"
        h="${foot_h}" o_x="${-foot_h}" o_y="${-foot_w}" o_z="${-foot_l}" o_r="0" o_p="0" o_yaw="0"
        mat="${foot_mat}"
        mesh_filename="${foot_mesh}" mirror="1" />

    <!-- ======================================================= -->
    <!-- JOINTS                                                  -->
    <!-- ======================================================= -->
    <xacro:macro name="create_leg" params="side origin_y">
        <!-- origin_y="${origin_y}" -->
        <xacro:create_joint name="${side}_pel_joint" parent="waist_link"
            child="${side}_pel_link" origin_x="0" origin_y="${origin_y}"
            origin_z="0" o_roll="0"
            o_pitch="0" o_yaw="0"
            axis_x="1" axis_y="0" axis_z="0"
            lower_limit="-1.5" upper_limit="1.5" effort="1000" velocity="10.0" />
        <xacro:create_joint name="${side}_hip_joint" parent="${side}_pel_link"
            child="${side}_thigh_link"
            origin_x="0" origin_y="0" origin_z="${-pel_l}" o_roll="0" o_pitch="0" o_yaw="0"
            axis_x="0" axis_y="1" axis_z="0"
            lower_limit="-${PI}" upper_limit="${PI}" effort="100000" velocity="100.0" />
        <!-- <xacro:create_joint name="${side}_hip_joint" parent="waist_link"
        child="${side}_thigh_link"
            origin_x="0" origin_y="${origin_y}" origin_z="0" o_roll="0" o_pitch="0" o_yaw="0"
            axis_x="0" axis_y="1" axis_z="0"
            lower_limit="-${PI}" upper_limit="${PI}" effort="100000" velocity="100.0" /> -->
        <xacro:create_joint name="${side}_kne_joint" parent="${side}_thigh_link"
            child="${side}_shank_link"
            origin_x="0" origin_y="0" origin_z="${-thigh_l}" o_roll="0" o_pitch="0" o_yaw="0"
            axis_x="0" axis_y="1" axis_z="0"
            lower_limit="-${PI}" upper_limit="${PI}" effort="100000" velocity="100.0" />
        <xacro:create_joint name="${side}_ank_joint" parent="${side}_shank_link"
            child="${side}_foot_link"
            origin_x="0" origin_y="0" origin_z="${-shank_l}" o_roll="0" o_pitch="${-PI/2}" o_yaw="0"
            axis_x="0" axis_y="1" axis_z="0"
            lower_limit="-1.75" upper_limit="1.75" effort="1000" velocity="10.0" />
    </xacro:macro>

    <xacro:property name="waist_w_offset" value="${waist_w * 0.42}" />
    <xacro:create_leg side="l" origin_y="${waist_w_offset}" />
    <xacro:create_leg side="r" origin_y="${-waist_w_offset}" />

    <!-- ======================================================= -->
    <!-- GAZEBO                                                  -->
    <!-- ======================================================= -->
    <gazebo>
        <plugin name="gazebo_ros2_control" filename="libgazebo_ros2_control.so">
            <parameters>$(find yr_lle_sim)/config/control.yaml</parameters>
        </plugin>
    </gazebo>

    <ros2_control name="MyRobotHardware" type="system">
        <hardware>
            <plugin>gazebo_ros2_control/GazeboSystem</plugin>
        </hardware>
        <joint name="l_hip_joint">
            <commandInterface>effort</commandInterface>
            <stateInterface>position</stateInterface>
            <stateInterface>velocity</stateInterface>
            <stateInterface>effort</stateInterface>
        </joint>
        <joint name="l_kne_joint">
            <commandInterface>effort</commandInterface>
            <stateInterface>position</stateInterface>
            <stateInterface>velocity</stateInterface>
            <stateInterface>effort</stateInterface>
        </joint>
    </ros2_control>

    <gazebo reference="l_thigh_link">
        <material>Gazebo/Blue</material>
    </gazebo>

    <gazebo reference="l_shank_link">
        <material>Gazebo/Green</material>
    </gazebo>

    <xacro:macro name="create_leg_transmissions" params="side">
        <xacro:create_transmission joint_name="${side}_hip_joint" />
        <xacro:create_transmission joint_name="${side}_kne_joint" />
        <!-- <xacro:create_transmission joint_name="${side}_ank_joint" /> -->
    </xacro:macro>

    <!-- <xacro:create_leg_transmissions side="l" />
    <xacro:create_leg_transmissions side="r" /> -->

</robot>